// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exam.Services.Database;

#nullable disable

namespace exam.Services.Migrations
{
    [DbContext(typeof(ExamContext))]
    partial class ExamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exam.Services.Database.FITPasos", b =>
                {
                    b.Property<int>("FITPasosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FITPasosId"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumVazenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("FITPasosId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("FITPasos");

                    b.HasData(
                        new
                        {
                            FITPasosId = 1,
                            Aktivan = true,
                            DatumVazenja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 5
                        },
                        new
                        {
                            FITPasosId = 2,
                            Aktivan = false,
                            DatumVazenja = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 6
                        },
                        new
                        {
                            FITPasosId = 3,
                            Aktivan = true,
                            DatumVazenja = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 7
                        });
                });

            modelBuilder.Entity("exam.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisniks");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            Email = "admin@admin.com",
                            Ime = "Admin",
                            KorisnickoIme = "admin",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Admin",
                            Telefon = "061399232",
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikId = 2,
                            Email = "uposlenik@uposlenik.com",
                            Ime = "Uposlenik",
                            KorisnickoIme = "uposlenik",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Uposlenik",
                            Telefon = "061399233",
                            UlogaId = 2
                        },
                        new
                        {
                            KorisnikId = 3,
                            Email = "korisnik@korisnik.com",
                            Ime = "Korisnik",
                            KorisnickoIme = "korisnik",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Korisnik",
                            Telefon = "061222333",
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikId = 4,
                            Email = "marko.markovic@example.com",
                            Ime = "Marko",
                            KorisnickoIme = "marko",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Marković",
                            Telefon = "061111111",
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikId = 5,
                            Email = "ivana.ivankovic@example.com",
                            Ime = "Ivana",
                            KorisnickoIme = "ivana",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Ivanković",
                            Telefon = "062222222",
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikId = 6,
                            Email = "petar.petrovic@example.com",
                            Ime = "Petar",
                            KorisnickoIme = "petar",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Petrović",
                            Telefon = "063333333",
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikId = 7,
                            Email = "ana.anic@example.com",
                            Ime = "Ana",
                            KorisnickoIme = "ana",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Anić",
                            Telefon = "064444444",
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikId = 8,
                            Email = "nikola.nikolic@example.com",
                            Ime = "Nikola",
                            KorisnickoIme = "nikola",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Nikolić",
                            Telefon = "065555555",
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikId = 9,
                            Email = "jelena.jelenkovic@example.com",
                            Ime = "Jelena",
                            KorisnickoIme = "jelena",
                            PasswordHash = "C5fuEDcAxNxDuUXqOJCU9DYfLpM=",
                            PasswordSalt = "qQ0nSvQ4rOy3pP/Zi95wIw==",
                            Prezime = "Jelenković",
                            Telefon = "066666666",
                            UlogaId = 3
                        });
                });

            modelBuilder.Entity("exam.Services.Database.MoodTracker", b =>
                {
                    b.Property<int>("MoodTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoodTrackerId"));

                    b.Property<DateTime>("DatumEvidencije")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("OpisRaspolozenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrijednostRaspolozenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoodTrackerId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("MoodTrackers");

                    b.HasData(
                        new
                        {
                            MoodTrackerId = 1,
                            DatumEvidencije = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 7,
                            OpisRaspolozenja = "Mnogo sretan",
                            VrijednostRaspolozenja = "Sretan"
                        },
                        new
                        {
                            MoodTrackerId = 2,
                            DatumEvidencije = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 9,
                            OpisRaspolozenja = "Mnogo tuzan",
                            VrijednostRaspolozenja = "Tuzan"
                        },
                        new
                        {
                            MoodTrackerId = 3,
                            DatumEvidencije = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 5,
                            OpisRaspolozenja = "Pod velikim stresom",
                            VrijednostRaspolozenja = "Pod_Stresom"
                        });
                });

            modelBuilder.Entity("exam.Services.Database.ToDo4924", b =>
                {
                    b.Property<int>("ToDo4924Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToDo4924Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KrajnjiRok")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivAktivnosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisAktivnosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAktivnosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToDo4924Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ToDo4924s");

                    b.HasData(
                        new
                        {
                            ToDo4924Id = 1,
                            KorisnikId = 4,
                            KrajnjiRok = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NazivAktivnosti = "Neka aktivnost",
                            OpisAktivnosti = "Opis neke aktivnosti",
                            StatusAktivnosti = "U_Toku"
                        },
                        new
                        {
                            ToDo4924Id = 2,
                            KorisnikId = 5,
                            KrajnjiRok = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NazivAktivnosti = "Neka aktivnost dva",
                            OpisAktivnosti = "Opis neke aktivnosti dva",
                            StatusAktivnosti = "Istekla"
                        },
                        new
                        {
                            ToDo4924Id = 3,
                            KorisnikId = 6,
                            KrajnjiRok = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NazivAktivnosti = "Neka aktivnost tri",
                            OpisAktivnosti = "Opis neke aktivnosti tri",
                            StatusAktivnosti = "Realizovana"
                        });
                });

            modelBuilder.Entity("exam.Services.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaId");

                    b.ToTable("Ulogas");

                    b.HasData(
                        new
                        {
                            UlogaId = 1,
                            Naziv = "Admin",
                            Opis = "Bog i batina."
                        },
                        new
                        {
                            UlogaId = 2,
                            Naziv = "Uposlenik",
                            Opis = "Tu i tamo moze nesto."
                        },
                        new
                        {
                            UlogaId = 3,
                            Naziv = "Korisnik",
                            Opis = "Obicni smrtnik."
                        });
                });

            modelBuilder.Entity("exam.Services.Database.FITPasos", b =>
                {
                    b.HasOne("exam.Services.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("exam.Services.Database.Korisnik", b =>
                {
                    b.HasOne("exam.Services.Database.Uloga", "Uloga")
                        .WithMany("Korisniks")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("exam.Services.Database.MoodTracker", b =>
                {
                    b.HasOne("exam.Services.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("exam.Services.Database.ToDo4924", b =>
                {
                    b.HasOne("exam.Services.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("exam.Services.Database.Uloga", b =>
                {
                    b.Navigation("Korisniks");
                });
#pragma warning restore 612, 618
        }
    }
}
